### ISSUE TITLE
namespace

### ISSUE THREAD

**Issue by mrepisch** [vpiotr/decimal_for_cpp#16]
Hello
Thx very mutch for your decimal_for_cpp. Its working great.
But there is one littel issue. 
If you use decimal_for_cpp with Qt you have to rename the namespace, because the namespace "dec"
is allready taken by Qt. 
You maybe consider to change that namespace name.

Regards Sascha

**Comment by vpiotr** [comment]
Hi, I'm not aware of any such cases. 
Could you send me a link to this existing namespace description?
I found only this: http://doc.qt.io/qt-5/namespaces.html
but it doesn't mention anything similar.

Regards, Piotr

**Comment by mrepisch** [comment]
Hello 
Since i allready renamed the namespace i can't recustruct witch class or namespace it was witch conflictet with your lib. It just was somthing with Qt thats for sure. i head to rename the namespace to "deci" and everything was fine. So no big deal. But its awsome to see that you put sutch effort in your code.
Thx very mutch mate.

Regards Sascha

**Comment by vpiotr** [comment]
Hi, from now you can use DEC_NAMESPACE symbol to define namespace you want to use for decimal.

Thanks, 
Piotr
