### ISSUE TITLE
How does it stand against Muller's recursion ?

### ISSUE THREAD

**Issue by X-Ryl669** [vpiotr/decimal_for_cpp#34]
To test the numerical precision of your implementation, there is a simple test to perform: compute Muller's recursion. 
This simple formula shows that usual floating point diverges rapidly from expected result.
Muller's formula is:

```
   f(y, z) = 108 - (815 - 1500/z) / y
   x_0 = 4
   x_1 = 4.25
   x_i = f(x_[i-1], x_[i-2])
```  
This formula has 2 poles: 5 and 100. Typically, if x happens to be 5, it'll stay 5. The closer it is to 5, the more likely it'll reach 5. Similarly, if x happens to be 100, it'll stay 100. 

The expected result with the starting values above should be 5, reached after 30 iterations.
Used with standard floating point, it's deviating and converging towards 100 rapidly.

See [my godbolt](https://gcc.godbolt.org/z/nA5bEH) for example code

**Comment by X-Ryl669** [comment]
I've [tested it](https://gcc.godbolt.org/z/eafgQ8) and it does not work well it seems.

**Comment by vpiotr** [comment]
Muller formula is designed for floating point numbers where rounding errors should be avoided.
In decimal data types situation is different - this data type *enforces* value roundings. 
Decimal type should be used for financial data (amounts, not ratings), where rounding is required by law.
See also: https://medium.com/@bellmar/is-cobol-holding-you-hostage-with-math-5498c0eb428b
