### ISSUE TITLE
specify decimal separator

### ISSUE THREAD

**Issue by Frafjord** [vpiotr/decimal_for_cpp#35]
in fromString and toString it would be nice to have the option of specifying decimal separator and thousand grouping directly as parameters.

Sometimes I want to parse with different settings than what my computer has.

I don't like to change my locale settings just to parse a few numbers with a different separator.

**Comment by vpiotr** [comment]
Hi, thanks for suggestion. I'll take a look at this.

**Comment by vpiotr** [comment]
Implemented requested change, see unit tests for examples.
Look for "decimal_format".
