### ISSUE TITLE
is there a way to perform assigment from std::string?

### ISSUE THREAD

**Issue by omerbrandis** [vpiotr/decimal_for_cpp#47]
Hello, 

[
these are my first steps with this lib ,
btw, its awesome , thanks for sharing it.
]

is there a way to perform assignment from std::string, something like 
DEC_NAMESPACE::decimal<8> TempDec8Value
for (...)
{
     TempDec8Value = std::string
}

thanks,
Omer.

**Comment by vpiotr** [comment]
Use fromString:

`TempDec8Value = dec::fromString<dec::decimal<8> >(str);`

See https://github.com/vpiotr/decimal_for_cpp/blob/master/tests/decimalTest.ipp
