### ISSUE TITLE
format_from_stream truncates its return value from decimal_format to basic_decimal_format

### ISSUE THREAD

**Issue by salvoilmiosi** [vpiotr/decimal_for_cpp#51]
https://github.com/vpiotr/decimal_for_cpp/blob/fe4a0bd8296a83b88c7b7d8a682f4cd864079248/include/decimal.h#L1637
https://github.com/vpiotr/decimal_for_cpp/blob/fe4a0bd8296a83b88c7b7d8a682f4cd864079248/include/decimal.h#L1648

`format_from_stream` should return `decimal_format`, not `basic_decimal_format`.
Since the function returns by value, it will be truncated.

**Comment by vpiotr** [comment]
Hi, thanks for submission but please provide test cases for which this fix corrects issues.

**Comment by salvoilmiosi** [comment]
```
#include "decimal.h"
#include <iostream>
#include <sstream>
#include <locale>

int main() {
    std::locale::global(std::locale("it_IT"));
    std::stringstream ss ("1.234,56");
    dec::decimal<2> ret;
    dec::fromStream (ss, ret);
    // ret should now be 1234.56
    std::cout << ret << std::endl;
    // 1.23
}
```
The problem is that fromStream internally calls format_from_stream that returns a decimal_format that is then truncated to basic_decimal_format. Then parse_unpacked calls its decimal_point and thousands_sep methods but no virtual dispatch is happening because the output is truncated since the function returns by value. Fixing that function fixes the issue.

**Comment by vpiotr** [comment]
Corrected in https://github.com/vpiotr/decimal_for_cpp/commit/98265a57385ec14ae84fc0b2b0f15c770b30f548
