### ISSUE TITLE
Enhancement: More friendly constructor

### ISSUE THREAD

**Issue by vrqq** [vpiotr/decimal_for_cpp#53]
Compile failure with that code:
```cpp
int main() {
    dec::decimal<2> vol = 1.002;
    vol = 100.015;
    std::cout<<vol<<std::endl;
    return 0;
}
```

```
./try_decimal.cpp:5:21: error: no viable conversion from 'double' to 'dec::decimal<2>'
    dec::decimal<2> vol = 1.002;
./decimal_for_cpp/include/decimal.h:667:5: note: candidate constructor not viable: no known conversion from 'double' to 'const dec::decimal<2, dec::def_round_policy> &' for 1st argument
    decimal(const decimal &src) = default;
```

The stackoverflow said that: https://stackoverflow.com/questions/21822438/in-copy-initialization-is-the-call-to-the-copy-constructor-explicit-or-implicit

**Comment by vpiotr** [comment]
Implicit conversion is not allowed in this library so your options are:

`dec::decimal<2> vol(1.002);`
or
`dec::decimal<2> vol = dec::decimal_cast<2>(1.002);`

This works without any problems:
`vol = 100.015;`
