### ISSUE TITLE
support for power and root ?

### ISSUE THREAD

**Issue by omerbrandis** [vpiotr/decimal_for_cpp#55]
hello,

I need to extract the root of a DEC_NAMESPACE, 
the standard sqrt operates on double.
`I was able to result = std::sqrt(Input.getAsDouble());`
but i guess i'm losing precision here somewhere...

please advise,
thanks,
Omer.

**Comment by Tanishq-Banyal** [comment]
@vpiotr ping!

**Comment by vpiotr** [comment]
Hi, sorry but I have no plans for sqrt, log or cbrt. 
I would go with the solution you mentioned.
