### ISSUE TITLE
Edge cases failing

### ISSUE THREAD

**Issue by HFTrader** [vpiotr/decimal_for_cpp#56]
Hey congrats for this work! I am using decimal_for_cpp for checking the results of some other algorithm (fpga) when I came across to a few test cases that are failing when apparently they should not. I want to check if this is expected behavior. For example:

```
BOOST_CHECK_EQUAL( dec::decimal<0>::buildWithExponent(1,-23), dec::decimal<0>("0"));
```

This test should not fail but it is right now. This can be seen as an underflow, right?

**Comment by vpiotr** [comment]
Hi, thanks. This value is out of range so it's not handled by the library. 
Maximum number of digits is 18 (because library is based on int64).
