### ISSUE TITLE
how to make nan value in decimal?

### ISSUE THREAD

**Issue by arjen-Lee1993** [vpiotr/decimal_for_cpp#64]
dec::decimal<10> num = std::numeric_limits<dec::decimal<10>>::quiet_NaN();
dec::decimal<10> num(std::numeric_limits<double>::quiet_NaN());
dec::decimal<10> num("nan");
all of these not work for std::isnan(num.getAsDouble()). is there any way to build a nan decimal value?

**Comment by vpiotr** [comment]
Hi, currently there is no support for NaN in this library.
Even if you pick a special value to support it, you would have to handle it in various places, for example in `multDiv` function.
This library also does not support division by zero, see:
`we don't check for division by zero, the caller should - the next line will`

One thing which can be done easy is to detect NaN at the initialization and reject such values. 
Please let me know if it will help in anything, I'll try to find a slot to implement such change.

**Comment by arjen-Lee1993** [comment]
thanks a lot for the reply. 
nan value just mean a invalid result in my work so i can work around it.
the current version can already support my work well ^-^
